"""Background music: one looping track per situation.

Built-in tracks live in kaiko/assets/ (generated by tools/make_music.py). A
file dropped into music/ with the same name, as .mp3, overrides one locally.
"""

from __future__ import annotations

from pathlib import Path

import pygame

MUSIC_DIR = Path(__file__).resolve().parent.parent / "music"
BUILTIN_DIR = Path(__file__).resolve().parent / "assets"
FADE_MS = 600


def track_for(state: str, boss_active: bool) -> str | None:
    """Which track should be playing. None means silence."""
    if state == "gameover":
        return None
    if state == "playing" and boss_active:
        return "boss"
    return "level"


def track_path(name: str, music_dir: Path = MUSIC_DIR, builtin_dir: Path = BUILTIN_DIR) -> Path | None:
    for path in (music_dir / f"{name}.mp3", builtin_dir / f"{name}.wav"):
        if path.is_file():
            return path
    return None


class Music:
    """Switches tracks only when the wanted one changes. Missing files or no
    audio device mean silence, never a crash."""

    def __init__(self, music_dir: Path = MUSIC_DIR, builtin_dir: Path = BUILTIN_DIR, log=print):
        self.music_dir = music_dir
        self.builtin_dir = builtin_dir
        self.log = log
        self.current: str | None = None
        self.enabled = self._init_mixer()
        self._warned: set[str] = set()

    def _init_mixer(self) -> bool:
        try:
            if not pygame.mixer.get_init():
                pygame.mixer.init()
        except pygame.error as exc:
            self.log(f"[kaiko] no audio device, music off ({exc})")
            return False
        return True

    def play(self, name: str | None) -> None:
        if name == self.current:
            return
        self.current = name
        if not self.enabled:
            return
        if name is None:
            pygame.mixer.music.fadeout(FADE_MS)
            return
        path = track_path(name, self.music_dir, self.builtin_dir)
        if path is None:
            if name not in self._warned:
                self._warned.add(name)
                self.log(f"[kaiko] no {name} music found, run tools/make_music.py")
            pygame.mixer.music.stop()
            return
        pygame.mixer.music.load(str(path))
        pygame.mixer.music.play(loops=-1, fade_ms=FADE_MS)
